// src/lib/renderers/pptx.js
// PPTX renderer using pptxgenjs, parameterised by Skill.

import pptxgen from 'pptxgenjs';

const THEMES = ['1F4E79', 'ED7D31', '70AD47', '7030A0', 'C00000'];

function sectionSlide(pres, title, skill) {
  const s = pres.addSlide();
  s.addShape(pres.ShapeType.rect, {
    x: 0, y: 0, w: 13.333, h: 0.6,
    fill: { color: skill.theme.primary },
  });
  s.addText(title, {
    x: 0.5, y: 1.0, w: 12, h: 1.2,
    fontSize: 36, bold: true, color: '333333',
    fontFace: skill.font.cnHeading,
  });
  return s;
}

function tableSlide(pres, title, headers, rows, themeIdx, skill) {
  const s = sectionSlide(pres, title, skill);
  const head = headers.map(h => ({ text: h, options: {
    bold: true, color: 'FFFFFF', fill: { color: THEMES[themeIdx % THEMES.length] },
    fontSize: 12, align: 'center', valign: 'middle',
    fontFace: skill.font.cnBody,
  }}));
  const body = rows.map(r => r.map(v => ({ text: String(v ?? ''), options: {
    fill: { color: 'F2F2F2' }, color: '333333', fontSize: 11, align: 'center', valign: 'middle',
    fontFace: skill.font.cnBody,
  }})));
  s.addTable([head, ...body], {
    x: 0.5, y: 2.8, w: 12.333, h: 4.2,
    border: { pt: 1, color: 'B4C7E7' },
  });
  return s;
}

export async function renderPptx(doc, skill) {
  const pres = new pptxgen();
  pres.layout = 'LAYOUT_WIDE';
  pres.title = doc.meta?.title ?? 'Generated by office-mcp';

  // cover
  if (doc.cover) {
    const s = pres.addSlide();
    s.background = { color: skill.theme.primary };
    s.addText(doc.cover.title, {
      x: 1, y: 2.5, w: 11.333, h: 1.5,
      fontSize: 44, bold: true, color: 'FFFFFF', align: 'center',
      fontFace: skill.font.cnHeading,
    });
    if (doc.cover.subtitle) {
      s.addText(doc.cover.subtitle, {
        x: 1, y: 4.5, w: 11.333, h: 0.8,
        fontSize: 22, color: 'CCDDEE', align: 'center',
      });
    }
  }

  let themeIdx = 0;
  for (const ch of doc.chapters ?? []) {
    if (ch.blocks?.some(b => b.type === 'table')) {
      // pick first table block
      const t = ch.blocks.find(b => b.type === 'table');
      tableSlide(pres, ch.title, t.headers ?? t.rows[0], t.rows.slice(1), themeIdx++, skill);
    } else if (ch.blocks?.some(b => b.type === 'flowchart')) {
      const fc = ch.blocks.find(b => b.type === 'flowchart');
      const s = sectionSlide(pres, ch.title, skill);
      const nodes = fc.nodes;
      const n = nodes.length;
      const margin = 0.5, gap = 0.3, nodeH = 2.0, top = 3.5;
      const nodeW = (13.333 - 2 * margin - gap * (n - 1)) / n;
      nodes.forEach((node, i) => {
        const x = margin + i * (nodeW + gap);
        s.addShape(pres.ShapeType.roundRect, {
          x, y: top, w: nodeW, h: nodeH,
          fill: { color: node.color }, line: { color: 'FFFFFF', width: 2 },
        });
        s.addText(node.label, {
          x, y: top, w: nodeW, h: nodeH,
          fontSize: 14, bold: true, color: 'FFFFFF', align: 'center', valign: 'middle',
          fontFace: skill.font.cnBody,
        });
        if (i < n - 1) {
          s.addShape(pres.ShapeType.line, {
            x: x + nodeW, y: top + nodeH / 2, w: gap, h: 0,
            line: { color: '333333', width: 2, endArrowType: 'triangle' },
          });
        }
      });
    } else if (ch.blocks?.some(b => b.type === 'code')) {
      for (const cb of ch.blocks.filter(b => b.type === 'code')) {
        const s = sectionSlide(pres, cb.title ?? ch.title, skill);
        s.addShape(pres.ShapeType.rect, {
          x: 0.4, y: 2.9, w: 12.533, h: 4.2,
          fill: { color: 'F2F2F2' }, line: { color: cb.borderColor ?? '5B9BD5', width: 2 },
        });
        s.addText(cb.code, {
          x: 0.5, y: 3.0, w: 12.333, h: 4.0,
          fontSize: 13, fontFace: 'Courier New', color: '1A1A1A', valign: 'top',
        });
      }
    } else if (ch.blocks?.some(b => b.type === 'list')) {
      const s = sectionSlide(pres, ch.title, skill);
      const items = ch.blocks.find(b => b.type === 'list').items.map(it => ({
        text: `• ${it}\n`, options: { fontSize: 22, fontFace: skill.font.cnBody, color: '333333' },
      }));
      s.addText(items, { x: 0.7, y: 3.0, w: 12, h: 4, valign: 'top', paraSpaceAfter: 16 });
    } else {
      // paragraph-only chapter: one slide with full text
      const s = sectionSlide(pres, ch.title, skill);
      const text = (ch.blocks ?? []).map(b => b.text ?? '').join('\n\n');
      s.addText(text, {
        x: 0.7, y: 3.0, w: 12, h: 4,
        fontSize: 20, fontFace: skill.font.cnBody, color: '333333', valign: 'top', paraSpaceAfter: 12,
      });
    }
  }

  const buffer = await pres.write({ outputType: 'arraybuffer' });
  return Buffer.from(buffer);
}
